name: Build InkGuru

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows App
        run: flutter build windows

      - name: Zip Windows Build
        run: Compress-Archive -Path build\windows\x64\runner\Release\* -DestinationPath inkguru-windows.zip

      - name: Upload Windows Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: inkguru-windows-app
          path: inkguru-windows.zip
